language: php
php:
- '5.6'
stages:
- name: test
- name: package
jobs:
  include:
  - stage: test
    before_install:
    - cp .env.example .env
    install:
    - composer install
  - stage: package
    script:
    - composer install
    - export build_date="$(date '+%y%m%d%H%M%S')"
    - tar -czf /tmp/${build_date}.tgz --exclude=.git* .
    - ls -ail /tmp
    - pip install --user awscli
    - "$HOME/.local/bin/aws s3 ls s3://csun-metalab-builds/"
env:
  global:
  - secure: mrhAc4G8MDObA2pOpYSAnQosIzEl4jiZ2koEhvN8IBbFXpvpvnWXPYqhB3FWNSCzlNu5zrYx68cQcNdfwrlL434GCxThwYsk2KeTi+8f1Zx80QvyGV3jfDxDaUMXUtTGyCVw2p+PdN9E+oBmkQLtjXhXLxQvbV4m6jiB0Zdb1phvb5f8C+FClnnWgyGv/L6zGu/i1t85x6hN9ZLZWd+fiIiiNiUFpVKWfoB1L464zwNi8d7Y4foLqr7iXigSW5cU/8f30dMEoZb80oNDkApfmWZyltBr6t9uKS0ikSnlEi8mytqphIVW2g0tdHMibTtu0VBykdOLNw6fxMho6zkZiTqhJIoRKfP8Thb0A9BTWhq9eki7Mx4+drcf8fXL/MEAK1W8+NzHWVogC55ai7tCrbgybTlcbAPdIOHeD+o3p6IEroB9Z2MkfMZLvLuLqND53sGWvZGcmqMlhSsqWigzWdoBJ7usBaA/ysZABUkF5Boi8BccE4A0egpvyex+1H5uau6jok7KhiNh6FdfP9slULSVTMh4uexpqxMzeioy7WofPhrlwps2Q4P4m0Hbj0z0luruTcdoJpJR6wajPuajEWhzdPfSCGfm3f0MhAmK7giLVqI9s4eMTHHrAy/LJhNngOBXQfUJ2b4qKILv1QXB2rnNGCh+ncTECBxDHFxyhLs=
  - secure: AaB+HpEQMGWLcEHi5KaH7DfDxIgPU6sq3JsD5cp7ToyVWwxCxBDZQSfYqLhgr3Eqmz632UykvAMXeHtyKk7QsnORLgopNMYo2a6tZk3dsWIZUKQpomW+5PocfJcIY28cyDwK/lZOef9jImg6cEiQaLgN/Dy+6eVh5MokIXY4e5auA4VveEPQPEcraoRqWhLQpD8EDjeitrUNMJUF7HZnbonlVA994OYSLjoxwc6krCE5jNzbPzMv5zNjruk5W0037AQQXIMRAiCnrfmmWr6mWvj5zwS/y6lrPuxl3/KOf7dPucU0Be2CT+1mZ3rT8DPrWEp+sn+xmJaiRMcXgdO7f8g9vYiHH2wfaqo06NyotOFTeV/7c/+waUy+sWGlJ5Gy/S6O7s5TJA2a3x8ihmu1tivRp0cFP4NPK9MBKF40nEsmj66cX7wA7Cy+JIGx8PEKQBHFyUs9yAzDYP3W7wKk+WZBeBBSECi7SxI3sRuVYd0mKBH+EO/H43QRVg1V3C4xRS1QnxcB4sFwQUHR8DLYju07LjpZJ5N9HnkuWBCFYLXuxHcH/A3GzHSQo5VvRthbMCHjdILfVXOTFT74b+9tgO8foZg5CtAGKJL53ab/8VmM4DTjDXYh4IQHZbXzJ56hKwKxxv/iuCzbKATOwQHaJScJySm3oroek+4IwstkHT8=
