version: '3'

services:
  webserver:
    container_name: degrees
    image: csunmetalab/api:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html

  composer:
    restart: 'no'
    container_name: degrees_composer
    image: composer:latest
    command: install
    volumes:
      - .:/app/
